In [5]:
import sys
sys.path.append("..")
import numpy as np
from qutip import *
import src.GRAPH_LDF as qrac
import src.Annealing as ann
#-------------------------------------------------------------------------------
# Graph definition and system parameters
#-------------------------------------------------------------------------------
# Define the graph matrix and the number of vertices
N_v = 10
adj_matrix = np.zeros((N_v,N_v))
adj_matrix[0] = np.array([0,1,1,1,0,0,0,0,0,0])
adj_matrix[1] = np.array([1,0,0,0,1,0,0,0,1,0])
adj_matrix[2] = np.array([1,0,0,0,0,0,1,1,0,0])
adj_matrix[3] = np.array([1,0,0,0,0,1,0,0,0,1])
adj_matrix[4] = np.array([0,1,0,0,0,1,0,1,0,0])
adj_matrix[5] = np.array([0,0,0,1,1,0,1,0,0,0])
adj_matrix[6] = np.array([0,0,1,0,0,1,0,0,1,0])
adj_matrix[7] = np.array([0,0,1,0,1,0,0,0,0,1])
adj_matrix[8] = np.array([0,1,0,0,0,0,1,0,0,1])
adj_matrix[9] = np.array([0,0,0,1,0,0,0,1,1,0])


qrac_mat, n_qbit, qbit_ord, features = qrac.QRAC_HAMILTONIAN(adj_matrix, N_v)
_, gs_vector = ann.Annealing_GS(qrac_mat, n_qbit, M=1, taumax=100.0, t_steps=1000)
gs_vector = gs_vector[0]
result, result_1 =  qrac.Graph_partition_func(gs_vector, N_v, qbit_ord, n_qbit, features)

--------------------
FEATURES=
 [[0 1 1 1 0 2 0 2 2 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 1 2 1 0 2 1 2 0]]
--------------------
Number of QBITS= 4
--------------------
Qbits ordering= [1 3 3 3 1 4 1 4 4 2]
--------------------
H_RELAX=
 [[-2.5+0.j -6. +3.j -9. +3.j  3. +0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j
  -3. +6.j  0. +0.j  0. +3.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j]
 [-6. -3.j -2.5+0.j -3. +0.j -3. +3.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j
  -6. +0.j  3. +0.j  0. +0.j  0. +3.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j]
 [-9. -3.j -3. +0.j  3.5+0.j  0. +3.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j
   0. -3.j  0. +0.j -3. +0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j]
 [ 3. +0.j -3. -3.j  0. -3.j  3.5+0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j
   0. +0.j  0. -3.j -6. +0.j  3. -6.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j]
 [ 0. +0.j  0. +0.j  0. +0.j  0. +0.j -2.5+0.j  0. -3.j -3. +3.j  3. +0.j
   0. +0.j  0. +0.j  0. +0.j  0. +0.j -3. +6.j  0. +0.j  0. +3.j  0. +0.j]
 [ 0. +0.j  0. +0.j  0.