In [2]:
import sys
sys.path.append("..")
import numpy as np
from qutip import *
import src.GRAPH_LDF as qrac
import src.Annealing as ann
#-------------------------------------------------------------------------------
# Graph definition and system parameters
#-------------------------------------------------------------------------------
# Define the graph matrix and the number of vertices
N_v = 10
adj_matrix = np.zeros((N_v,N_v))
adj_matrix[0] = np.array([0,1,1,1,0,0,0,0,0,0])
adj_matrix[1] = np.array([1,0,0,0,1,0,0,0,1,0])
adj_matrix[2] = np.array([1,0,0,0,0,0,1,1,0,0])
adj_matrix[3] = np.array([1,0,0,0,0,1,0,0,0,1])
adj_matrix[4] = np.array([0,1,0,0,0,1,0,1,0,0])
adj_matrix[5] = np.array([0,0,0,1,1,0,1,0,0,0])
adj_matrix[6] = np.array([0,0,1,0,0,1,0,0,1,0])
adj_matrix[7] = np.array([0,0,1,0,1,0,0,0,0,1])
adj_matrix[8] = np.array([0,1,0,0,0,0,1,0,0,1])
adj_matrix[9] = np.array([0,0,0,1,0,0,0,1,1,0])

# adj_matrix[0] = np.array([0,0,0,1,0])
# adj_matrix[1] = np.array([0,0,0,1,1])
# adj_matrix[2] = np.array([0,0,0,0,1])
# adj_matrix[3] = np.array([1,1,0,0,1])
# adj_matrix[4] = np.array([0,1,1,1,0])

# adj_matrix[0] = np.array([0,1,1])
# adj_matrix[1] = np.array([1,0,1])
# adj_matrix[2] = np.array([1,1,0])

#adj_matrix[0] = np.array([0,1])
#adj_matrix[1] = np.array([1,0])

qrac_mat, n_qbit, qbit_ord, features = qrac.QRAC_HAMILTONIAN(adj_matrix, N_v)
print(n_qbit)

--------------------
FEATURES=
 [[0 1 1 1 0 2 0 2 2 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 1 2 1 0 2 1 2 0]]
--------------------
Number of QBITS= 4
--------------------
Qbits ordering= [1 3 3 3 1 4 1 4 4 2]
--------------------
H_RELAX=
 [[-2.5+0.j -6. +3.j -9. +3.j  3. +0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j
  -3. +6.j  0. +0.j  0. +3.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j]
 [-6. -3.j -2.5+0.j -3. +0.j -3. +3.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j
  -6. +0.j  3. +0.j  0. +0.j  0. +3.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j]
 [-9. -3.j -3. +0.j  3.5+0.j  0. +3.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j
   0. -3.j  0. +0.j -3. +0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j]
 [ 3. +0.j -3. -3.j  0. -3.j  3.5+0.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j
   0. +0.j  0. -3.j -6. +0.j  3. -6.j  0. +0.j  0. +0.j  0. +0.j  0. +0.j]
 [ 0. +0.j  0. +0.j  0. +0.j  0. +0.j -2.5+0.j  0. -3.j -3. +3.j  3. +0.j
   0. +0.j  0. +0.j  0. +0.j  0. +0.j -3. +6.j  0. +0.j  0. +3.j  0. +0.j]
 [ 0. +0.j  0. +0.j  0.

In [3]:
# Find the Ground State using the Annealing method
# H1_matrix, N, M, taumax, t_steps
_, gs_vector = ann.Annealing_GS(qrac_mat, n_qbit, M=1, taumax=100.0, t_steps=1000)
gs_vector = gs_vector[0]
print(gs_vector)

[-9.20347061e-05-6.24773669e-06j -5.52684968e-05-4.78810825e-05j
 -4.40722109e-05-3.28178142e-05j  1.30873085e-05-2.82615271e-05j
  4.17269628e-02+1.28645875e-02j  1.27264821e-01-2.58609749e-01j
  1.67454067e-02-1.03356609e-01j -2.19793383e-01+2.78498612e-01j
 -3.03517557e-05-4.43321865e-05j -1.46995061e-06-1.57877175e-05j
 -1.65757702e-05-4.03781886e-05j  6.43639939e-06-1.51571267e-06j
 -7.35831876e-02-1.92048298e-01j -3.05037974e-01+1.96502228e-01j
 -3.85539277e-01+2.90735920e-01j  6.09145436e-01+0.00000000e+00j]


In [4]:
result, result_1 =  qrac.Graph_partition_func(gs_vector, N_v, qbit_ord, n_qbit, features)
print(result)

[1 1 0 1 0 1 1 0 1 1]
